#!/bin/sh
# Install coddl's git hooks. Idempotent — re-run any time (e.g. after cloning).
#
# Writes a thin .git/hooks/pre-commit shim that execs the tracked hook. This
# deliberately does NOT set core.hooksPath, so any local hooks already in
# .git/hooks (e.g. the ctags post-* hooks) keep firing.
set -e

repo="$(git rev-parse --show-toplevel)"
shim="$repo/.git/hooks/pre-commit"

if [ -e "$shim" ] && ! grep -q 'tools/git-hooks/pre-commit' "$shim" 2>/dev/null; then
    echo "warning: $shim already exists and isn't ours — overwriting." >&2
fi

cat > "$shim" <<'SH'
#!/bin/sh
# Auto-generated by tools/git-hooks/install.sh — edit tools/git-hooks/pre-commit instead.
exec "$(git rev-parse --show-toplevel)/tools/git-hooks/pre-commit" "$@"
SH
chmod +x "$shim"

echo "installed: .git/hooks/pre-commit -> tools/git-hooks/pre-commit"
